(define (problem ten-cities)
	(:domain agencia_viajes)
	(:objects
		c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 - ciudad
		h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17 h18 h19 h20 - hotel
	)
	(:init
		(conectada c1 c4)
		(conectada c1 c5)
		(conectada c1 c6)
		(conectada c1 c9)
		(conectada c1 c10)
		(conectada c2 c1)
		(conectada c2 c4)
		(conectada c2 c5)
		(conectada c2 c9)
		(conectada c3 c1)
		(conectada c3 c2)
		(conectada c3 c7)
		(conectada c3 c8)
		(conectada c3 c10)
		(conectada c4 c3)
		(conectada c5 c9)
		(conectada c6 c4)
		(conectada c6 c10)
		(conectada c7 c1)
		(conectada c7 c5)
		(conectada c7 c6)
		(conectada c7 c8)
		(conectada c7 c9)
		(conectada c7 c10)
		(conectada c8 c2)
		(conectada c8 c4)
		(conectada c8 c6)
		(conectada c8 c10)
		(conectada c9 c6)
		(conectada c9 c8)
		(conectada c10 c2)
		(conectada c10 c9)
		(hotel_ciudad c1 h1)
		(hotel_ciudad c1 h2)
		(hotel_ciudad c1 h3)
		(hotel_ciudad c1 h4)
		(hotel_ciudad c1 h5)
		(hotel_ciudad c2 h6)
		(hotel_ciudad c2 h7)
		(hotel_ciudad c2 h8)
		(hotel_ciudad c2 h9)
		(hotel_ciudad c2 h10)
		(hotel_ciudad c2 h11)
		(hotel_ciudad c2 h12)
		(hotel_ciudad c3 h13)
		(hotel_ciudad c4 h14)
		(hotel_ciudad c5 h15)
		(hotel_ciudad c6 h16)
		(hotel_ciudad c7 h17)
		(hotel_ciudad c8 h18)
		(hotel_ciudad c9 h19)
		(hotel_ciudad c10 h20)

		(= (numero_ciudades_visitadas) 0)
		(= (numero_minimo_dias_por_ciudad) 1)
		(= (numero_maximo_dias_por_ciudad) 3)

		(= (numero_interes c1) 2)
		(= (numero_interes c2) 3)
		(= (numero_interes c3) 3)
		(= (numero_interes c4) 3)
		(= (numero_interes c5) 1)
		(= (numero_interes c6) 3)
		(= (numero_interes c7) 3)
		(= (numero_interes c8) 2)
		(= (numero_interes c9) 3)
		(= (numero_interes c10) 1)
		(= (numero_interes-total) 0)

	)
	(:goal
		(and
		(= (numero_ciudades_visitadas) 4)
		(>= (numero_dias_viaje) 5)
		(>= (numero_dias_ciudad) (numero_minimo_dias_por_ciudad))
		)
	)
	(:metric minimize (numero_interes-total))
)

