(define (problem ten-cities)
	(:domain agencia_viajes)
	(:objects
		c1 c2 c3 c4 c5 - ciudad
		h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 - hotel
	)
	(:init
		(conectada c1 c2)
		(conectada c2 c3)
		(conectada c3 c4)
		(conectada c3 c5)
		(conectada c4 c1)
		(conectada c5 c1)
		(hotel_ciudad c1 h1)
		(hotel_ciudad c1 h2)
		(hotel_ciudad c1 h3)
		(hotel_ciudad c1 h4)
		(hotel_ciudad c1 h5)
		(hotel_ciudad c1 h6)
		(hotel_ciudad c2 h7)
		(hotel_ciudad c3 h8)
		(hotel_ciudad c4 h9)
		(hotel_ciudad c5 h10)

		(= (numero_ciudades_visitadas) 0)
		(= (numero_minimo_dias_por_ciudad) 2)
		(= (numero_maximo_dias_por_ciudad) 4)

		(= (precio-hotel h1) 241)
		(= (precio-hotel h2) 58)
		(= (precio-hotel h3) 105)
		(= (precio-hotel h4) 301)
		(= (precio-hotel h5) 154)
		(= (precio-hotel h6) 295)
		(= (precio-hotel h7) 125)
		(= (precio-hotel h8) 75)
		(= (precio-hotel h9) 378)
		(= (precio-hotel h10) 323)
		(= (precio-hotel-total) 0)
		(= (numero_minimo_precio_hoteles) 2000)
		(= (numero_maximo_precio_hoteles) 2200)

		(= (precio-viaje c1 c2) 232)
		(= (precio-viaje c2 c3) 328)
		(= (precio-viaje c3 c4) 142)
		(= (precio-viaje c3 c5) 187)
		(= (precio-viaje c4 c1) 173)
		(= (precio-viaje c5 c1) 117)
		(= (precio-viaje-total) 0)
	)
	(:goal
		(and
		(= (numero_ciudades_visitadas) 4)
		(hotel_asignado)
		(>= (numero_dias_viaje) 10)
		(>= (numero_dias_ciudad) (numero_minimo_dias_por_ciudad))
		(>= (+ (precio-hotel-total) (precio-viaje-total)) (numero_minimo_precio_hoteles))
		(<= (+ (precio-hotel-total) (precio-viaje-total)) (numero_maximo_precio_hoteles))
		)
	)
	(:metric minimize (+ (* 1 (precio-hoteles-total)) (* 1 (precio-viaje-total)) ))
)

